spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  freemarker:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      bcg:
        test:
          settleshop:
            mapper: DEBUG
    org.springframework.boot.autoconfigure: ERROR
debug: true
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://212.129.144.221:3306/settle_shop?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: appAdmin
    password: Abc123..
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 50
      max-active: 200
      max-idle: 200
      min-idle: 10
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
      idle-timeout: 120000
      connection-timeout: 6000
      maxIdleTime: 60
server:
  port: 8210